# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  UmbraCore_config = debug
  UmbraEditor_config = debug
  UmbraSandbox_config = debug

else ifeq ($(config),release)
  UmbraCore_config = release
  UmbraEditor_config = release
  UmbraSandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := UmbraCore UmbraEditor UmbraSandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

UmbraCore:
ifneq (,$(UmbraCore_config))
	@echo "==== Building UmbraCore ($(UmbraCore_config)) ===="
	@${MAKE} --no-print-directory -C UmbraCore -f Makefile config=$(UmbraCore_config)
endif

UmbraEditor:
ifneq (,$(UmbraEditor_config))
	@echo "==== Building UmbraEditor ($(UmbraEditor_config)) ===="
	@${MAKE} --no-print-directory -C UmbraEditor -f Makefile config=$(UmbraEditor_config)
endif

UmbraSandbox: UmbraCore
ifneq (,$(UmbraSandbox_config))
	@echo "==== Building UmbraSandbox ($(UmbraSandbox_config)) ===="
	@${MAKE} --no-print-directory -C UmbraSandbox -f Makefile config=$(UmbraSandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C UmbraCore -f Makefile clean
	@${MAKE} --no-print-directory -C UmbraEditor -f Makefile clean
	@${MAKE} --no-print-directory -C UmbraSandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   UmbraCore"
	@echo "   UmbraEditor"
	@echo "   UmbraSandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"